### ISSUE TITLE
build-loader Pyhton code not working

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/c4ddev#12]
Need to investigate this. In C4D, I get

```
Traceback (most recent call last):
  File "'loader.pyp'", line 252, in <module>
  File "<string>", line 42, in <module>
  File "<string>", line 152
    _urllib_parse_moved_attributes=[MovedAttribute("ParseResult","urlparse","urllib.parse"),MovedAttribute("SplitResult","urlparse","urllib.parse"),MovedAttribute("parse_qs","urlparse","urllib.parse"),MovedAttribute("parse_qsl","urlparse","urllib.parse"),MovedAttribute("urldefrag","urlparse","urllib.parse"),MovedAttribute("urljoin","urlparse","urllib.parse"),MovedAttribute("urlparse","urlparse","urllib.parse"),MovedAttribute("urlsplit","urlparse","urllib.parse"),MovedAttribute("urlunparse","urlparse","urll
ib.parse"),MovedAttribute("urlunsplit","urlparse","urllib.parse"),MovedAttribute("quote","urllib","urllib.parse"),MovedAttribute("quote_plus","urllib","urllib.parse"),MovedAttribute("unquote","urllib","urllib.parse"),MovedAttribute("unquote_plus","urllib","urllib.parse"),MovedAttribute("urlencode","urllib","urllib.parse"),MovedAttribute("splitquery","urllib","urllib.parse"),MovedAttribute("splittag","urllib","urllib.parse"),MovedAttribute("splituser","urllib","urllib.parse"),MovedAttribute("uses_fragment",
"urlparse","urllib.parse"),MovedAttribute("uses_netloc","urlparse","urllib.parse"),MovedAttribute("uses_params","urlparse","urllib.parse"),MovedAttribute("uses_query","urlparse","urllib.parse"),MovedAttribute("uses_relative","urlparse","urllib.parse"),]
                                 ^
IndentationError: expected an indented block
```

Try to run the code as is via standard Python gives

```
Traceback (most recent call last):
  File "test.py", line 1630, in <module>
    exec(b.b64decode(blob), vars(m)); nodepy=m; del blob, b, t, m;
  File "<string>", line 832, in <module>
NameError: name '__file__' is not defined
```

**Comment by NiklasRosenstein** [comment]
The `__file__` error is due to the `nodepy` module referencing the `__file__` variable. Fixed this in `@nodepy/standalone-builder@0.0.5` where blobs inherit the parent scope's `__file__` value.

The other error seems to be an issue with pyminifier (and eventually only Python 2). Not using the minifier works.
